build:
  image: ruby:2
  commands:
    - bundle install --without development
    - bundle exec rake syntax
    - bundle exec rake lint
deploy:
  ssh:
    host: cm.chriscowley.lan
    user: drone
    port: 22
    commands:
      - /opt/puppetlabs/puppet/bin/r10k deploy environment $$BRANCH -p -v -c /etc/puppetlabs/r10k/r10k.yaml
notify:
  webhook:
    urls:
      - http://192.168.1.3:5000
    content_type: application/yaml
    template: >
        repo: {{ repo.full_name }}
        branch: {{ build.branch }}
