build:
  image: ruby:2.1.3
  commands:
    - bundle install
    - bundle exec rake syntax
    - bundle exec rake lint
deploy:
  ssh:
    host: cm.chriscowley.lan
    user: drone
    port: 22
    commands:
      - /opt/puppetlabs/puppet/bin/r10k deploy environment $$BRANCH -p -v -c /etc/puppetlabs/r10k/r10k.yaml
