mod 'puppetlabs/puppetdb', '4.2.1'
mod 'puppetlabs/stdlib', '4.6.0'
mod 'puppetlabs/inifile', '1.2.0'
mod 'puppetlabs/firewall', '1.5.0'
mod 'puppetlabs/postgresql', '4.3.0'
mod 'puppetlabs/apt', '2.0.1'
mod 'puppetlabs/concat', '1.2.1'
mod 'puppetlabs/apache', '1.4.1'
mod 'stankevich/python', '1.9.4'
mod 'puppetlabs/vcsrepo', '1.2.0'
mod 'nibalizer/puppetboard', '2.5.0'

